version 0.2
run-as: root

phases: 
  install:
    runtime-version:
      nodejs: 12
    commands:
      - npm install -g serverless@2.21.1
      - npm update --save
      - npm audit fix
  build:
    commands:
      - serverless deploy
cache:
  paths:
    - node_modules